# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/crossword-generator',
                'doc_host': 'https://netzzwergeGithub.github.io',
                'git_url': 'https://github.com/netzzwergeGithub/crossword-generator',
                'lib_path': 'crossword_generator'},
  'syms': {'crossword_generator.core': {'crossword_generator.core.foo': ('core.html#foo', 'crossword_generator/core.py')}}}
