"""Creates from a pattern-string with placeholders possible subpaterns that matches possible placement spaces for a a crossword generator"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_pattern_generator.ipynb.ipynb.

# %% auto 0
__all__ = ['PatternGenerator']

# %% ../nbs/01_pattern_generator.ipynb.ipynb 2
from fastcore.foundation import L

# %% ../nbs/01_pattern_generator.ipynb.ipynb 4
class PatternGenerator:
    def __init__(self, slot_pattern, min_word_length=2, space_char=' '):
        self.slot_pattern = slot_pattern
        self.min_word_length = min_word_length
        self.space_char = space_char
    
    def generate_patterns(self):
        # Returns sorted list of (offset, pattern)
        patterns = list(self._extract_subpatterns())
        patterns.sort(key=lambda x: x[2], reverse=True)  # Sort by sort_key
        return list(L(patterns).map(lambda x: x[:2]))
    
    def _extract_subpatterns(self):
        only_spaces = all([self.space_char == x for x in self.slot_pattern.split()])
        patterns = L()
        
        for i in range(len(self.slot_pattern) + 1 - self.min_word_length):
            for j in range(i + self.min_word_length, len(self.slot_pattern) + 1):
                part_pat = self.slot_pattern[i:j]
                
                if (i == 0 or self.slot_pattern[i-1] == self.space_char) and \
                   (j == len(self.slot_pattern) or self.slot_pattern[j] == self.space_char):
                    sort_key = self._make_sort_key(part_pat, i)
                    patterns.append((i, part_pat, sort_key))
        
        if not only_spaces:
            patterns = patterns.filter(lambda y: not all([self.space_char == x for x in y[1].split()]))
        return set(patterns)
    
    def _make_sort_key(self, part_pattern, offset):
        pos_t = self._get_position_type(offset, len(part_pattern))
        cross_count = self._count_constraints(part_pattern)
        pat_len = len(part_pattern)
        return "%s_%03x_%03x" % (pos_t, cross_count, pat_len)
    
    def _count_constraints(self, pattern):
        return len(pattern.replace(self.space_char, ''))
    
    def _get_position_type(self, offset, pattern_length):
        if offset == 0:
            return 's'
        if offset + pattern_length == len(self.slot_pattern):
            return 'l'
        return 'i'
